# Copyright 1999-2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.1.0.9999

CABAL_FEATURES=""
inherit haskell-cabal

DESCRIPTION="GHC build system"
HOMEPAGE="https://gitlab.haskell.org/ghc/ghc/-/tree/master/hadrian#readme"
SRC_URI="https://eidetic.codes/${P}-src-gentoo.tar.xz"

LICENSE="BSD"
SLOT="0"
KEYWORDS=""
IUSE="+threaded"

PATCHES=(
#	"${FILESDIR}/${PN}-9.0.2-newer-cabal.patch"
	"${FILESDIR}/${PN}-9.0.2-no-profiling-flavour.patch"
)

CABAL_CHDEPS=(
#	'Cabal                >= 3.0     && < 3.3' 'Cabal >= 3.0'
#	'QuickCheck           >= 2.6     && < 2.14' 'QuickCheck >= 2.6'
#	'shake                >= 0.18.3  && < 0.18.6' 'shake >= 0.18.3'
#	'happy >= 1.19.10 && < 1.20' 'happy >= 1.19.10'
)

RDEPEND="
	>=dev-haskell/cabal-3.2:= <dev-haskell/cabal-3.7:=
	>=dev-haskell/extra-1.4.7:=
	>=dev-haskell/quickcheck-2.6:2= <dev-haskell/quickcheck-2.15:2=
	>=dev-haskell/unordered-containers-0.2.1:= <dev-haskell/unordered-containers-0.3:=
	>=dev-lang/ghc-8.4.3:=
	>=dev-util/shake-0.18.3:= <dev-util/shake-0.20:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.2.0.1
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag threaded threaded)
}
