# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.7.3.0

CABAL_FEATURES=""
inherit haskell-cabal

DESCRIPTION="GHC build system"
HOMEPAGE="https://gitlab.haskell.org/ghc/ghc/-/blob/ghc-9.4.2-release/README.md"

REPO_NAME="ghc"
REPO_URI="https://gitlab.haskell.org/ghc/${REPO_NAME}"
COMMIT="e8a889a7fc670532a3bf883a3e25acba92e6e6e1"
BRANCH="ghc-9.4"

#if use bootstrap; then
#	SRC_URI="${REPO_URI}/-/archive/${COMMIT}/${REPO_NAME}-${COMMIT}.tar.gz"
#else
#	# TODO: Set up something similar to 'arch_binaries' from the ghc ebuild
#	SRC_URI="https://eidetic.codes/${PN}-bin-${PV}-x86_64-pc-linux-gnu.tbz2"
#fi

SRC_URI="${REPO_URI}/-/archive/${COMMIT}/${REPO_NAME}-${COMMIT}.tar.gz"
S="${WORKDIR}/${REPO_NAME}-${COMMIT}/${PN}"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="bootstrap test +threaded"
RESTRICT+=" !test? ( test )"
REQUIRED_USE="test? ( bootstrap )"

RDEPEND="
	bootstrap? (
		>=dev-haskell/cabal-3.2:= <dev-haskell/cabal-3.7:=
		>=dev-haskell/extra-1.4.7:=
		>=dev-haskell/unordered-containers-0.2.1:= <dev-haskell/unordered-containers-0.3:=
		>=dev-lang/ghc-8.4.3:=
		>=dev-util/shake-0.18.3:= <dev-util/shake-0.20:=
		test? ( >=dev-haskell/quickcheck-2.6:2= <dev-haskell/quickcheck-2.15:2= )
	)
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.2.0.1
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag test selftest) \
		$(cabal_flag threaded threaded)
}
